### PR TITLE
Proposal to create a roadmap

### PR DESCRIPTION
**Pull request by GeorgLink**
Hi everyone,

Moving this work forward, it would be good to have a roadmap.
What do we want to achieve?
When do we realistically can achieve our goals?

It would be great if we can set milestones and a tentative release date.
To accomplish our goals, we can also decide on a regular work patterns (e.g., regular calls, emails, ...).

Once we have the roadmap, we can choose responsibilities and focus on getting work done.

Thoughts?

### CODE REVIEW

**Comment by germonprez** [comment]
Super, duper +1 on this. Excellent idea @GeorgLink

**Comment by GeorgLink** [comment]
I think I heard a talk about roadmaps at FOSDEM and how important they are 🥇 (not my idea)

**Comment by germonprez** [comment]
Well, we're creating the one for CHAOSS as a whole so why not the projects too? Again, good idea.

**Comment by GeorgLink** [comment]
We decided on goals and next meeting in #8

**Pull request closed without merging**
